[tox]
envlist = py38,py39,py310,py311,py312

[testenv]
deps = 
    setuptools<81
    -r requirements-dev.txt
commands = python -m pytest tests/ .

[testenv:py310]
commands =
    python -m pytest \
        --cov=nornir_ansible \
        --cov-report html \
        --cov-report term \
        tests/ .
    python -m isort -c .
    python -m black --check .
    python -m pylama .
    python -m pydocstyle .
    python -m mypy nornir_ansible/
